#!/usr/bin/env bash

echo "prepare..."
rm -rf dist
mkdir -p dist

echo "building curegex.ls / curegex.tw.ls -> dist ... "

npx webpack

echo "copy dist to web ..."
rm -rf web/static/assets/lib/curegex/dev/
mkdir -p web/static/assets/lib/curegex/dev/
cp -R dist/* web/static/assets/lib/curegex/dev/
